---
deployment:
  tasks:
    - export DEPLOYPATH=/home/heydarnd/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH